# Introduction to Numpy


In [2]:
import numpy as np
import sys

# Array Creation

* List -> Array

In [3]:
my_list1=[1,2,3,4,5]
array1=np.array(my_list1)
print(f"{array1}")
print(f"{sys.getsizeof(my_list1)}\n{sys.getsizeof(array1)}")

[1 2 3 4 5]
104
152


* Zero Array

In [4]:
zeroArray1=np.zeros(5)
print(zeroArray1)
print("------------------")
zeroArray2=np.zeros((5,5))
print(zeroArray2)

[0. 0. 0. 0. 0.]
------------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


* Ones Array


In [5]:
onesArray1=np.ones(5)
print(onesArray1)
print("-----------------------------")
onesArray2=np.ones((5,5))
print(onesArray2)

[1. 1. 1. 1. 1.]
-----------------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


* Full with 'Values'[eg. 2,3,4,56,7,0,1]

In [6]:
full1=np.full(5,100)
print(full1)

[100 100 100 100 100]


In [7]:
full2=np.full((5,5),9)
print(full2)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


* Numpy Eye

In [8]:
identityMetrix1=np.eye(4)
print(identityMetrix1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* linespace

In [9]:
aLinespaceVariable1=np.linspace(0,100,21)
print(aLinespaceVariable1)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


* arange


In [10]:
m=np.arange(1,19)
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* Random of Numpy


In [11]:
randomNumber1=np.random.randint(10,99)
print(randomNumber1)

28


In [41]:
n=np.random.rand(10)
print(n)

[0.83264695 0.7425632  0.48861453 0.20384691 0.82734034 0.6565459
 0.77405183 0.64880424 0.47421341 0.32397881]


In [42]:
nMeshGrid=np.meshgrid(n)
print(nMeshGrid)

(array([0.83264695, 0.7425632 , 0.48861453, 0.20384691, 0.82734034,
       0.6565459 , 0.77405183, 0.64880424, 0.47421341, 0.32397881]),)


In [43]:
np.random.randn()

1.8585156382982475

# Array Manupulation Functions

* Reshape

In [47]:
np.reshape(identityMetrix1,(8,2))

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

* Ravel (For Flatten)

In [48]:
np.ravel(identityMetrix1)

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

* Flatten

In [51]:
full2.flatten()

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9])

* Transpose

In [64]:
x=np.array([[1,2,3],[7,8,9],[4,5,6]])
print(x)


k=np.transpose(x)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
